### ISSUE TITLE
Install error could not find module 'q'

### ISSUE THREAD

**Issue by rolinger** [adriano-di-giovanni/cordova-plugin-enable-multidex#5]
Was installing latest version and got the following error:

```
cordova plugin add cordova-plugin-enable-multidex
Installing "cordova-plugin-enable-multidex" for android
Android Studio project detected
Subproject Path: CordovaLib
Subproject Path: app
Failed to install 'cordova-plugin-enable-multidex': Error: Cannot find module 'q'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at module.exports (C:\Users\RPO\dev\myapp.2.85\plugins\cordova-plugin-enable-multidex\scripts\android\editManifest.js:4:13)
    at runScriptViaModuleLoader (C:\Users\RPO\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:188:18)
    at runScript (C:\Users\RPO\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:164:16)
    at C:\Users\RPO\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:132:20
    at _fulfilled (C:\Users\RPO\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\RPO\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:816:30)
(node:18308) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Cannot find module 'q'
```

I rolled back to 0.1.3 and it installed and compiled cleanly

**Comment by NathanR1225** [comment]
When I added  "q": "^1.5.1", to my package it fixed all of my q issues. I upgraded my project from Cordova 8 to Cordova  10. To do this I also had to change  ctx.requireCordovaModule('q')  to equire('q') in resolveDependencies.js, restoreBackups.js and  
 applyCustomConfig.js located at plugins -> cordova-custom-config -> hooks. Hope that helps.
